working_directory: /home/pablorr24/snake_folder

database_path: "/home/pablorr24/snake_folder/databases/silva/centrifuge"
#database_path:  "/home/pablorr24/Documents/silva_for_centrifuge"

#sample_path: /home/pablorr24/snake_folder/data/long_reads
sample_path: /home/pablorr24/Documents/benchmarking_files/long_reads_benchmarking/data #/10_zymo_ont.fastq

