working_directory: /home/pablorr24/snake_folder

database_path: "/home/pablorr24/snake_folder/databases/greengenes" # greengenes or silva

sample_path: /home/pablorr24/snake_folder/data/short_reads
#sample_path: /home/pablorr24/Desktop/workflow_test_greengenesG

trimmomatic_params:
  LEADING: 3
  TRAILING: 3
  SLIDINGWINDOW: "4:15"
  MINLEN: 36
  ADAPTERS: /home/pablorr24/snake_folder/data/adapters/TruSeq3-SE.fa #if no adapters are used, select 'None'

kraken_paired: true 
 
kraken_params:
  CONFIDENCE_INTERVAL: 0.2
  MIN_BASE_QUALITY: 0
    
 
alpha_diversity: "all" #options: all, Shannon, Simpson, Fischer, BP (Berger-Parkers) 


#Taxonomic Level to classify samples (S, G, O, C, F) for Species, Class, Order, Genus, Family...
otu_table_level: "S"

