#Run the short-reads full workflow by configuring these file and typing in the terminal
#snakemake -s Snakefile_fastqc --cores all 

working_directory: /home/snakemake_metagenomics

sample_path: /home/snakemake_metagenomics/data/short_reads/


