#Run the long-reads QC-only workflow by configuring these file and typing in the terminal
#snakemake -s Snakefile_nanoplot --cores all 

working_directory: /home/snakemake_metagenomics

sample_path: /home/snakemake_metagenomics/data/long_reads
